services:
  backend:
    image: ghcr.io/lobovvit/lovit-backend:${BUILD_VERSION}
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILD_VERSION=${BUILD_VERSION}
    restart: unless-stopped
    ports:
      - "8080:8080"